CXXFLAGS = `gsl-config --cflags` -g -pedantic #-fopenmp# -I ./libbci-1.1.0/ 
LDFLAGS = `gsl-config --libs` -lm 

SOURCES = amplitudelib/main.cpp amplitudelib/amplitudelib.cpp amplitudelib/datafile.cpp src/interpolation.cpp src/tools.cpp
OBJECTS = $(SOURCES:.cpp=.o)

all: amplitudelib 

amplitudelib: $(OBJECTS)
	g++ $(CXXFLAGS) $(LDFLAGS) $(OBJECTS) -o amplitude
.cpp.o:
	 g++ $(CXXFLAGS) $< -c -o $@
.c.o:
	gcc $(CXXFLAGS) $< -c -o $@

clean:
	rm -f $(OBJECTS)
	rm -f amplitude	
