CXXFLAGS = `gsl-config --cflags` -O2 -fopenmp -pedantic -I ../amplitudelib  
LDFLAGS = `gsl-config --libs`  

include filelist.m

CC = icc
CXX = icpc
FORT = ifort

all: rbk

rbk: $(OBJECTS) 
	$(CXX) $(OBJECTS) $(LDFLAGS) $(CXXFLAGS) -o rbk 
.cpp.o:
	$(CXX) $(CXXFLAGS) $< -c -o $@
.c.o:
	$(CC) $(CXXFLAGS) $< -c -o $@

clean:
	rm -f $(OBJECTS) $(AMPLITUDELIBO)
	rm -f rbk	
