CXXFLAGS = `gsl-config --cflags` -O3 -fopenmp -pedantic -I ../amplitudelib #-fopenmp# -I ./libbci-1.1.0/ 
LDFLAGS = `gsl-config --libs`  

include filelist.m

CC = icc
CXX = icpc
FORT = ifort

all: rbk

rbk: $(OBJECTS) 
	$(CXX) $(OBJECTS) $(LDFLAGS) $(CXXFLAGS) -o rbk 
.cpp.o:
	$(CXX) $(CXXFLAGS) $< -c -o $@
.c.o:
	$(CC) $(CXXFLAGS) $< -c -o $@

clean:
	rm -f $(OBJECTS) $(AMPLITUDELIBO)
	rm -f bk	
